#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_plot_xy.plot_xy import PlotXY

plugin = 'rqt_plot_xy.plot_xy.PlotXY'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=PlotXY.add_arguments))
